import type { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import BackgroundDecor from "../Components/BackgroundDecor/BackgroundDecor";
import Header from "../Components/Header/Header";
import Footer from "../Components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: { locale?: string };
};
export default async function RootLayout({ children, params }: Props) {
  const  locale  = "en" ;
  const messages = await getMessages({ locale });
  console.log(locale);
  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cream-bg font-sans text-gray-800 min-h-screen flex flex-col relative overflow-x-hidden`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
